---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - wordpress.digihunch.com
  resources:
  - wordpresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wordpress.digihunch.com
  resources:
  - wordpresses/finalizers
  verbs:
  - update
- apiGroups:
  - wordpress.digihunch.com
  resources:
  - wordpresses/status
  verbs:
  - get
  - patch
  - update
